DEFAULT_TRAITS = {
    "extraversion": "A measure of how outgoing, sociable, and assertive a person is.",
    "agreeableness": "A measure of how cooperative, friendly, and compassionate a person is.",
    "openness": "A measure of how open a person is to new experiences, ideas, and creativity.",
    "conscientiousness ": "A measure of how organized, responsible, and reliable a person is.",
    "emotional_stability": "A measure of how emotionally stable and calm a person is in stressful situations.",
    "intuition": "A preference for focusing on abstract, theoretical concepts and possibilities.",
    "thinking": "A preference for making decisions based on objective logic and analysis",
    "assertiveness": "A measure of how confident, decisive, and self-assured a person is",
    "empathy": "A measure of how well a person can understand and share the feelings of others",
    "adaptability": "A measure of how well a person can adjust to new situations and environments",
    "risk-taking": "A measure of how willing a person is to take risks and engage in adventurous activities",
    "ambition": "A measure of how driven, goal-oriented, and persistent a person is in pursuing their objectives",
    "feeling": "A preference for making decisions based on subjective values and emotions.",
    "altruism": "A measure of a person's selflessness and willingness to help others without expecting anything in return.",
    "curiosity": "A measure of a person's desire to explore, learn, and seek new experiences.",
    "creativity": "A measure of a person's ability to think in novel ways, generate original ideas, and solve problems.",
    "optimism": "A measure of a person's tendency to maintain a positive outlook and expect favorable outcomes.",
    "pessimism": "A measure of a person's tendency to focus on negative aspects and expect unfavorable outcomes.",
    "introversion": "A measure of how reserved, introspective, and comfortable a person is with solitude.",
    "humility": "A measure of a person's modesty, willingness to admit mistakes, and recognition of their limitations.",
    "patience": "A measure of a person's ability to remain calm and composed during delays, difficulties, or provocation.",
    "resilience": "A measure of a person's ability to recover quickly from setbacks and adapt to change.",
    "self-discipline": "A measure of a person's ability to control their impulses, desires, and behaviors in order to achieve long-term goals.",
    "social_awareness": "A measure of a person's ability to understand and navigate social situations and group dynamics.",
    "spirituality": "A measure of a person's belief in, or connection to, a higher power, transcendent values, or a sense of meaning and purpose.",
    "independence": "A measure of a person's desire for autonomy, self-reliance, and personal freedom.",
    "loyalty": "A measure of a person's commitment, fidelity, and devotion to a person, group, or cause.",
    "perfectionism": "A measure of a person's insistence on high standards, attention to detail, and striving for flawlessness.",
    "sense_of_humor": "A measure of a person's ability to perceive, appreciate, and express humor in various situations.",
    "tolerance": "A measure of a person's acceptance and openness to differing opinions, beliefs, and lifestyles.",
    "charisma": "A measure of a person's ability to inspire, influence, and connect with others through personal charm and presence.",
    "courage": "A measure of a person's ability to face fear, danger, or adversity with bravery and determination.",
    "competitiveness": "A measure of a person's desire to outperform others and achieve success in challenging situations."
}
